version: '2'

services:

  peer1.org1.persistent.com:
    container_name: peer1.org1.persistent.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.persistent.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.persistent.com:8051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_default
    ports:
      - 8051:8051
      - 8053:8053
    volumes:
        - ./crypto-config/peerOrganizations/org1.persistent.com/peers/peer1.org1.persistent.com/:/etc/hyperledger/crypto/peer
    extra_hosts:
        - "orderer.ordererorg.persistent.com:10.53.18.198"
