version: '2'

services:

  orderer.ordererorg.persistent.com:
    container_name: orderer.ordererorg.persistent.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_default
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerOrg1/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./configtx:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/ordererorg.persistent.com/orderers/orderer.ordererorg.persistent.com:/etc/hyperledger/crypto/orderer
        - ./crypto-config/peerOrganizations/org1.persistent.com/peers/peer0.org1.persistent.com/:/etc/hyperledger/crypto/peerOrg1
        - ./crypto-config/peerOrganizations/org2.persistent.com/peers/peer0.org2.persistent.com/:/etc/hyperledger/crypto/peerOrg2

    extra_hosts:
      - "peer0.org1.persistent.com:10.53.20.105"
      - "peer0.org2.persistent.com:10.53.20.154"
